filebeat.inputs:
  - type: log
    enabled: true
    json.keys_under_root: true
    json.add_error_key: true
    tags: [ "dcache_api" ]
    paths:
      - /var/log/dcache_api/*.log
  - type: log
    enabled: true
    json.keys_under_root: true
    json.add_error_key: true
    tags: [ "dcache_rpc" ]
    paths:
      - /var/log/dcache_rpc/*.log
  - type: log
    enabled: true
    json.keys_under_root: true
    json.add_error_key: true
    tags: [ "cloud_service_rpc" ]
    paths:
      - /var/log/cloud_service_rpc/*.log
  - type: log
    enabled: true
    json.keys_under_root: true
    json.add_error_key: true
    tags: [ "merchant_manage_rpc" ]
    paths:
      - /var/log/merchant_manage_rpc/*.log
  - type: log
    enabled: true
    json.keys_under_root: true
    json.add_error_key: true
    tags: [ "store_manage_api" ]
    paths:
      - /var/log/store_manage_api/*.log
  - type: log
    enabled: true
    json.keys_under_root: true
    json.add_error_key: true
    tags: [ "store_manage_rpc" ]
    paths:
      - /var/log/store_manage_rpc/*.log
  - type: log
    enabled: true
    json.keys_under_root: true
    json.add_error_key: true
    tags: [ "tax_equ_manage_api" ]
    paths:
      - /var/log/tax_equ_manage_api/*.log
  - type: log
    enabled: true
    json.keys_under_root: true
    json.add_error_key: true
    tags: [ "tax_equ_manage_rpc" ]
    paths:
      - /var/log/tax_equ_manage_rpc/*.log

setup.template.settings:
  index.number_of_shards: 1

# 定义kafka topic field
fields:
  log_topic: log-collection

# 输出到kafka
output.kafka:
  hosts: ["kafka1:9092"]
  topic: '%{[fields.log_topic]}'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  keep_alive: 10s

# ================================= Processors =================================
processors:
  - decode_json_fields:
      fields: ['@timestamp','level','content','trace','span','duration']
      target: ""
      max_depth: 1